name: CI

on:
    pull_request:
    push:

jobs:
    lint:
        name: Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.4.0

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 19

            - name: Install NPM dependencies
              uses: pnpm/action-setup@v2
              with:
                  run_install: true
                  version: 8

            - name: Run ESLint
              run: pnpm run eslint
    build:
        name: Compilation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.4.0

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 19

            - name: Install NPM dependencies
              uses: pnpm/action-setup@v2
              with:
                  run_install: true
                  version: 8

            - name: Install roblox-ts
              run: pnpm install -g roblox-ts

            - name: Compile
              run: pnpm run build
