name: CI

on:
    pull_request:
    push:

jobs:
    lint:
        name: Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.4.0

            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.10

            - name: Run ESLint
              run: npm run eslint
    build:
        name: Compilation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.4.0

            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.10

            - name: Compile
              run: npm run build
